In [1]:
import numpy as np
a = np.array([0,1,2,3])

In [2]:
L = range(1000)
%timeit [i**2 for i in L]

361 µs ± 6.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.4 µs ± 20.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [4]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [5]:
a.ndim

1

In [6]:
a.shape

(4,)

In [7]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
len(b)

2

In [12]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [18]:
#using linspace (linear space)
a = np.linspace(0,1,6)#start, end, no. of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
c = np.eye(3)# return a 2-D array with ones on the diagonal and zero elements else where
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
c = np.eye(3,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [24]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
a = np.random.rand(4)
a

array([0.61043036, 0.72219234, 0.09414622, 0.12551558])

In [39]:
a = np.random.randn(4)
a.var()

0.27956725670625654

In [40]:
a = np.arange(10)
a.dtype

dtype('int32')

In [41]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [45]:
d = np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [46]:
b = np.array([True,False])
b.dtype

dtype('bool')

In [47]:
a = np.arange(10)
a[5]

5

In [49]:
a = np.diag([1,2,3])
a[2,2]

3

In [51]:
a[2,1] = 10
a

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0, 10,  3]])

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[1:8:2]

array([1, 3, 5, 7])

In [55]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [58]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [60]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [63]:
np.shares_memory(a,b)

True

In [64]:
b[2] = 10
a

array([ 0,  1,  2,  3, 10,  5,  6,  7,  8,  9])

In [66]:
a = np.arange(10)

In [67]:
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [68]:
c[2] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a = np.random.randint(0,20,15)
a

array([15, 18,  4,  3,  4,  9,  8, 14, 15, 18, 10, 12, 19, 18, 13])

In [73]:
mask = (a%2==0)

In [74]:
extract_from_a = a[mask]
extract_from_a

array([18,  4,  4,  8, 14, 18, 10, 12, 18])

In [75]:
a[mask] = -1
a

array([15, -1, -1,  3, -1,  9, -1, -1, 15, -1, -1, -1, 19, -1, 13])

In [76]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [77]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [78]:
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])